# Generated by Django 3.2.9 on 2021-12-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meals',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.food'),
        ),
    ]
