# Generated by Django 3.2.9 on 2021-12-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_meals_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Breakfast', max_length=10),
        ),
    ]
