# Generated by Django 3.2.9 on 2021-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211215_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='meal',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], default='B', max_length=100),
        ),
    ]
